### PR TITLE
Add basic documentation

### PR DESCRIPTION
**Pull request by aboucaud**
This PR aims at creating a  website to document galcheat and showcase some exemple of usage.

### CODE REVIEW

**Comment by mpaillassa** [comment]
I remember from our BTK meeting it looked good, but what is the link to the doc ? (Maybe we should add it in the README).

**Comment by aboucaud** [comment]
You're right, but I wait for publishing it that it looks good as it is.

**Comment by aboucaud** [comment]
Also I'm wondering if there's still a need for the `data/README.md` once the doc is live.

Because having redundant info at several places is usually a good way too forget something :)

**Comment by mpaillassa** [comment]
> You're right, but I wait for publishing it that it looks good as it is.

Ok but is it possible to access it before it's published ? Currently I have error 404 when going to the link. Or maybe I have to setup something to view it ?

> Also I'm wondering if there's still a need for the `data/README.md` once the doc is live.
> 
> Because having redundant info at several places is usually a good way too forget something :)

Yes indeed.

**Comment by aboucaud** [comment]
> Ok but is it possible to access it before it's published ? Currently I have error 404 when going to the link. Or maybe I have to setup something to view it ?

Right, sorry.

```
pip install -r docs/requirements.txt
mkdocs serve
```

**Comment by aboucaud** [comment]
> I tested:
> 
> ```
> python -m pip install -U galcheat
> python -m pip install -U scripts
> python -m pip install -U dev
> ```
> 
> But there may be an issue with `dev` was not found.

That's because the use of these extra install is 
```
python -m pip install -U galcheat[scripts]
python -m pip install -U galcheat[dev]
```
I might do the same with 'docs'

**Comment by aboucaud** [comment]
> * The `description` field is not in `docs/parameters.md`. Is it intentional ?

Nope, that's because I started writing the docs before it was added.
Thanks.

**Comment by mpaillassa** [comment]
> > I tested:
> > ```
> > python -m pip install -U galcheat
> > python -m pip install -U scripts
> > python -m pip install -U dev
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But there may be an issue with `dev` was not found.
> 
> That's because the use of these extra install is
> 
> ```
> python -m pip install -U galcheat[scripts]
> python -m pip install -U galcheat[dev]
> ```
> 
> I might do the same with 'docs'

Oh yes I thought that the brackets were for replacement but it is the exact command..

**Comment by aboucaud** [comment]
> * There may be a missing newline somewhere because the `LSST.get_filters()` line in the getting started is printed as:

It's a side effect of the `__repr__` definition I changed for the CLI to be printed nicely, and does not go well when being printed from within a dictionary. 
I might actually try to make a difference between `__str__` and `__repr__` to avoid such cases.

**Comment by aboucaud** [comment]
I am merging this now and will keep updating the docs till the release.

**Pull request merged**
